tasks:
  - command: minio server ${MINIO_VOLUMES}
    name: MinIO Server
  - command: adminio
    name: AdminIO Server
  - command: npx angular-http-server -p ${ADMINIO_UI_PORT} --path ${ADMINIO_UI_PATH}
    name: AdminIO-UI Server
  - init: make install_linux
image:
  file: .devcontainer/Dockerfile
