tasks:
  - command: minio server ${MINIO_VOLUMES}
    name: MinIO Server
  - init: make install_linux
image:
  file: .devcontainer/Dockerfile
vscode:
  extensions:
    - hashicorp.terraform@2.3.0:KgEabs4baG2MuLl5VL6Iyg==