version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2020-04-04T05-39-31Z
    hostname: minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_HTTP_TRACE: /dev/stdout
    command: server /data
  adminio-ui:
    image: rzrbld/adminio-ui:release-0.94
    ports:
      - "80:80"
  adminio-api:
    image: rzrbld/adminio-api:release-0.93
    environment:
      MINIO_ACCESS: minio
      MINIO_SECRET: minio123
      MINIO_HOST_PORT: minio:9000
      ADMINIO_HOST_PORT: :8080
    depends_on:
      - minio
      - adminio-ui
    ports:
      - "8080:8080"