name: Terraform Provider CI
on:
  push:
    branches:
      - master
      - feature/**
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint Golang Code
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:
      - name: Set up Go 
        uses: actions/setup-go@v1
        with:
          go-version: ${{ secrets.GO_VERSION }}
        id: go

      - name: Check out code
        uses: actions/checkout@v1
        with:
            fetch-depth: 1

      - name: Install tools
        run: |
          curl -sfL https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2
    
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 
        uses: actions/setup-go@v1
        with:
          go-version: ${{ secrets.GO_VERSION }}
        id: go
        
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
            fetch-depth: 1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: make build
